<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Yujia Yan - Example Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Yujia Yan</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About Me</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Example Analysis.html" aria-current="page">Example Analysis</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#research-question" id="toc-research-question" class="nav-link active" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#intended-audience" id="toc-intended-audience" class="nav-link" data-scroll-target="#intended-audience">Intended Audience</a></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis">Data Analysis</a>
  <ul class="collapse">
  <li><a href="#data-source" id="toc-data-source" class="nav-link" data-scroll-target="#data-source">Data Source</a></li>
  <li><a href="#data-dictionary" id="toc-data-dictionary" class="nav-link" data-scroll-target="#data-dictionary">Data Dictionary</a></li>
  <li><a href="#data-analysis-1" id="toc-data-analysis-1" class="nav-link" data-scroll-target="#data-analysis-1">Data Analysis</a></li>
  </ul></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"></a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2"></a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3"></a></li>
  <li><a href="#section-4" id="toc-section-4" class="nav-link" data-scroll-target="#section-4"></a>
  <ul class="collapse">
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#functions-used" id="toc-functions-used" class="nav-link" data-scroll-target="#functions-used">Functions used</a></li>
  <li><a href="#referneces" id="toc-referneces" class="nav-link" data-scroll-target="#referneces">Referneces</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Example Analysis</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/image2.jpeg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Baltimore weather</figcaption><p></p>
</figure>
</div>
<section id="research-question" class="level2">
<h2 class="anchored" data-anchor-id="research-question">Research Question</h2>
<p>In investigating whether particulate air pollution levels as measured by TSP are associated with mortality, it is important to control for seasonal variations that might reflect the effects of weather on mortality, rather than particulate pollution levels.</p>
<p>In this project, I will use daily data from the city of Baltimore for the period 1987-2005, including the mortality count, median PM10 level, and season, to investigate whether or not particulate air pollution is associated with mortality, having controlled for seasonal effects.</p>
</section>
<section id="intended-audience" class="level2">
<h2 class="anchored" data-anchor-id="intended-audience">Intended Audience</h2>
<p>Students who are studying statistical methods and environmental health.</p>
</section>
<section id="data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis">Data Analysis</h2>
<section id="data-source" class="level3">
<h3 class="anchored" data-anchor-id="data-source">Data Source</h3>
<p>This data comes from the <a href="https://www.healtheffects.org/publication/national-morbidity-mortality-and-air-pollution-study-part-iii-concentration-response">National Morbidity and Mortality Air Pollution Study</a> (NMMAPS) which looked at the relationship between pollution and health outcomes for 100 U.S. cities.</p>
</section>
<section id="data-dictionary" class="level3">
<h3 class="anchored" data-anchor-id="data-dictionary">Data Dictionary</h3>
<table class="table">
<caption>Table: Data Dictionary</caption>
<colgroup>
<col style="width: 23%">
<col style="width: 37%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Description</th>
<th>Coding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>date</td>
<td>Calender date</td>
<td>Date written in year, month, day</td>
</tr>
<tr class="even">
<td>deaths</td>
<td>Number of non-accidental deaths</td>
<td>Discrete</td>
</tr>
<tr class="odd">
<td>PM10</td>
<td>Particulate pollution level</td>
<td>Continuous</td>
</tr>
<tr class="even">
<td>temp</td>
<td>Temperature (Fahrenheit)</td>
<td>Continuous</td>
</tr>
<tr class="odd">
<td>season</td>
<td>Season of the year</td>
<td>1 = Winter 2 = Spring 3 = Summer 4 = Autumn</td>
</tr>
</tbody>
</table>
</section>
<section id="data-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="data-analysis-1">Data Analysis</h3>
<ol type="1">
<li>Stratify the daily mortality data into 4 groups by season.</li>
</ol>
<details>
<summary>
Click to show or hide code
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>balt621 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"balt621.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 6940 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): date, season
dbl (3): death, pm10, tempf

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>balt621 <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(season) <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n_pm10 =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(pm10)), <span class="at">mean_pm10 =</span> <span class="fu">mean</span>(pm10, <span class="at">na.rm=</span><span class="cn">TRUE</span>),                 <span class="at">n_mortality =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(death)), <span class="at">mean_mortality =</span> <span class="fu">mean</span>(death))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  season n_pm10 mean_pm10 n_mortality mean_mortality
  &lt;chr&gt;   &lt;int&gt;     &lt;dbl&gt;       &lt;int&gt;          &lt;dbl&gt;
1 Autumn    559    -2.97         1748           19.2
2 Spring    563     0.740        1729           18.2
3 Summer    571     4.58         1748           17.7
4 Winter    551    -2.93         1715           20.8</code></pre>
</div>
</div>
</details></section>
</section>
<section id="section" class="level1">
<h1></h1>
<table class="table">
<thead>
<tr class="header">
<th>season</th>
<th>n_pm10</th>
<th>mean_pm10</th>
<th>n_mortality</th>
<th>mean_mortality</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Autumn</td>
<td>559</td>
<td>-2.97</td>
<td>1748</td>
<td>19.2</td>
</tr>
<tr class="even">
<td>Spring</td>
<td>563</td>
<td>0.740</td>
<td>1729</td>
<td>18.2</td>
</tr>
<tr class="odd">
<td>Summer</td>
<td>571</td>
<td>4.58</td>
<td>1748</td>
<td>17.7</td>
</tr>
<tr class="even">
<td>Winter</td>
<td>551</td>
<td>-2.93</td>
<td>1715</td>
<td>20.8</td>
</tr>
</tbody>
</table>
<p>Looking at the summaries by season, we can see that mean daily mortality varies across the seasons – the lowest average daily mortality is in summer (17.7 deaths per day), followed by spring (18.2 deaths day), autumn (19.2 deaths per day), and winter (20.8 deaths per day). There is a reverse trend in PM10 levels: summer has the highest mean PM10 level (4.6), followed by spring (0.7), and autumn and winter (-3.0 for each).</p>
<p>The PM10 variable has been standardized so that values greater than 0 represent “above average” pollution days and values less that 0 represent “below average” pollution days. So summer tends to have pollution levels that are above average while autumn and winter have pollution levels that are below average.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>We also see that there is a lot of missing data for the PM10 variable. We see this because in winter, for example, there are 1,715 observations for death, but only 551 for pm10. There are only PM10 levels for about 30% of the days in the dataset.</p>
<p>The good news is that we see similar trends for death by season if we restrict to just the death data where we have PM10 data as well. We see that summer has the lowest average daily death rate, followed by spring, autumn, and winter. This means there’s nothing “unusual” about the days where we have missing PM10 data, so it’s to base our analysis only on the days where we have PM10 data.</p>
</div>
</div>
</div>
<details>
<summary>
Click to show or hide code
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>balt621 <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(pm10)) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(season) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n_pm10 =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(pm10)), <span class="at">mean_pm10 =</span> <span class="fu">mean</span>(pm10, <span class="at">na.rm=</span><span class="cn">TRUE</span>), </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">n_mortality =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(death)), <span class="at">mean_mortality =</span> <span class="fu">mean</span>(death))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  season n_pm10 mean_pm10 n_mortality mean_mortality
  &lt;chr&gt;   &lt;int&gt;     &lt;dbl&gt;       &lt;int&gt;          &lt;dbl&gt;
1 Autumn    559    -2.97          559           19.9
2 Spring    563     0.740         563           18.9
3 Summer    571     4.58          571           18.6
4 Winter    551    -2.93          551           21.5</code></pre>
</div>
</div>
</details></section>
<section id="section-1" class="level1">
<h1></h1>
<ol start="2" type="1">
<li>For each of the four seasonal strata, stratify the days into 5 pollution (pm10) strata and calculate the mean mortality in the lowest and highest of the five pollution strata separately for four seasonal strata.</li>
</ol>
<details>
<summary>
Click to show or hide code
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>pm10winter <span class="ot">&lt;-</span> <span class="fu">filter</span>(balt621, season<span class="sc">==</span><span class="st">"Winter"</span>) </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>quintiles <span class="ot">=</span> <span class="fu">quantile</span>(pm10winter<span class="sc">$</span>pm10, <span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">2</span>,.<span class="dv">4</span>,.<span class="dv">6</span>,.<span class="dv">8</span>,<span class="dv">1</span>), <span class="at">na.rm=</span><span class="cn">TRUE</span>) </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>pm10winter<span class="sc">$</span>pm_group <span class="ot">=</span> <span class="fu">cut</span>(pm10winter<span class="sc">$</span>pm10, <span class="at">breaks=</span>quintiles, <span class="at">labels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pm10winter<span class="sc">$</span>pm_group)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4   5 
110 110 110 110 110 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>pm10spring <span class="ot">&lt;-</span> <span class="fu">filter</span>(balt621, season<span class="sc">==</span><span class="st">"Spring"</span>) </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>quintiles <span class="ot">=</span> <span class="fu">quantile</span>(pm10spring<span class="sc">$</span>pm10, <span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">2</span>,.<span class="dv">4</span>,.<span class="dv">6</span>,.<span class="dv">8</span>,<span class="dv">1</span>), <span class="at">na.rm=</span><span class="cn">TRUE</span>) </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>pm10spring<span class="sc">$</span>pm_group <span class="ot">=</span> <span class="fu">cut</span>(pm10spring<span class="sc">$</span>pm10, <span class="at">breaks=</span>quintiles, <span class="at">labels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pm10spring<span class="sc">$</span>pm_group)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4   5 
112 112 113 112 113 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>pm10summer <span class="ot">&lt;-</span> <span class="fu">filter</span>(balt621, season<span class="sc">==</span><span class="st">"Summer"</span>) </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>quintiles <span class="ot">=</span> <span class="fu">quantile</span>(pm10summer<span class="sc">$</span>pm10, <span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">2</span>,.<span class="dv">4</span>,.<span class="dv">6</span>,.<span class="dv">8</span>,<span class="dv">1</span>), <span class="at">na.rm=</span><span class="cn">TRUE</span>) </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>pm10summer<span class="sc">$</span>pm_group <span class="ot">=</span> <span class="fu">cut</span>(pm10summer<span class="sc">$</span>pm10, <span class="at">breaks=</span>quintiles, <span class="at">labels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pm10summer<span class="sc">$</span>pm_group)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4   5 
114 114 114 114 114 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>pm10autumn <span class="ot">&lt;-</span> <span class="fu">filter</span>(balt621, season<span class="sc">==</span><span class="st">"Autumn"</span>) </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>quintiles <span class="ot">=</span> <span class="fu">quantile</span>(pm10autumn<span class="sc">$</span>pm10, <span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">2</span>,.<span class="dv">4</span>,.<span class="dv">6</span>,.<span class="dv">8</span>,<span class="dv">1</span>), <span class="at">na.rm=</span><span class="cn">TRUE</span>) </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>pm10autumn<span class="sc">$</span>pm_group <span class="ot">=</span> <span class="fu">cut</span>(pm10autumn<span class="sc">$</span>pm10, <span class="at">breaks=</span>quintiles, <span class="at">labels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pm10autumn<span class="sc">$</span>pm_group)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4   5 
111 112 111 112 112 </code></pre>
</div>
</div>
</details></section>
<section id="section-2" class="level1">
<h1></h1>
<p>In winter, the mean daily mortality is HIGHER on the low pollution days (22.2 vs.&nbsp;21.4 deaths.)</p>
<p>In spring, the mean daily mortality is LOWER on the low pollution days (18.6 vs.&nbsp;19.0 deaths.)</p>
<p>In summer, the mean daily mortality is LOWER on the low pollution days (17.7 vs.&nbsp;19.9 deaths.)</p>
<p>In autumn, the mean daily mortality is LOWER on the low pollution days (19.8 vs.&nbsp;20.6 deaths.)</p>
<details>
<summary>
Click to show or hide code
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>pm10winter <span class="sc">%&gt;%</span> <span class="fu">filter</span>(pm_group<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarize</span>(<span class="at">mean=</span><span class="fu">mean</span>(death), <span class="at">sd=</span><span class="fu">sd</span>(death), <span class="at">n=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
   mean    sd     n
  &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1  22.2  5.30   110</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>pm10winter <span class="sc">%&gt;%</span> <span class="fu">filter</span>(pm_group<span class="sc">==</span><span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarize</span>(<span class="at">mean=</span><span class="fu">mean</span>(death), <span class="at">sd=</span><span class="fu">sd</span>(death), <span class="at">n=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
   mean    sd     n
  &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1  21.4  5.35   110</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>pm10spring <span class="sc">%&gt;%</span> <span class="fu">filter</span>(pm_group<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarize</span>(<span class="at">mean=</span><span class="fu">mean</span>(death), <span class="at">sd=</span><span class="fu">sd</span>(death), <span class="at">n=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
   mean    sd     n
  &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1  18.6  4.19   112</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>pm10spring <span class="sc">%&gt;%</span> <span class="fu">filter</span>(pm_group<span class="sc">==</span><span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarize</span>(<span class="at">mean=</span><span class="fu">mean</span>(death), <span class="at">sd=</span><span class="fu">sd</span>(death), <span class="at">n=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
   mean    sd     n
  &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1  19.0  5.01   113</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>pm10summer <span class="sc">%&gt;%</span> <span class="fu">filter</span>(pm_group<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarize</span>(<span class="at">mean=</span><span class="fu">mean</span>(death), <span class="at">sd=</span><span class="fu">sd</span>(death), <span class="at">n=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
   mean    sd     n
  &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1  17.6  4.15   114</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>pm10summer <span class="sc">%&gt;%</span> <span class="fu">filter</span>(pm_group<span class="sc">==</span><span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarize</span>(<span class="at">mean=</span><span class="fu">mean</span>(death), <span class="at">sd=</span><span class="fu">sd</span>(death), <span class="at">n=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
   mean    sd     n
  &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1  19.9  5.68   114</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>pm10autumn <span class="sc">%&gt;%</span> <span class="fu">filter</span>(pm_group<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarize</span>(<span class="at">mean=</span><span class="fu">mean</span>(death), <span class="at">sd=</span><span class="fu">sd</span>(death), <span class="at">n=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
   mean    sd     n
  &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1  19.8  5.38   111</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>pm10autumn <span class="sc">%&gt;%</span> <span class="fu">filter</span>(pm_group<span class="sc">==</span><span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarize</span>(<span class="at">mean=</span><span class="fu">mean</span>(death), <span class="at">sd=</span><span class="fu">sd</span>(death), <span class="at">n=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
   mean    sd     n
  &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1  20.5  5.43   112</code></pre>
</div>
</div>
</details></section>
<section id="section-3" class="level1">
<h1></h1>
<ol start="3" type="1">
<li>Within each seasonal stratum, test the null hypothesis that the mean mortality is the same regardless of the pollution level by comparing the mean mortality in the lowest and highest pollution strata.</li>
</ol>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Given the large sample sizes, there is no need to pool the variances.</p>
</div>
</div>
</div>
<p>For all strata except summer, there is little indication of a difference in mean daily mortality between the lowest and highest pollution strata (p=0.22 for winter, p=0.48 for spring, p=0.33 for autumn). In summer, a difference in mean daily mortality between the lowest and highest pollution strata is strongly indicated (p=0.0006).</p>
<details>
<summary>
Click to show or hide code
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>pm10winter<span class="fl">.15</span> <span class="ot">=</span> pm10winter <span class="sc">%&gt;%</span> <span class="fu">filter</span>(pm_group<span class="sc">==</span><span class="dv">1</span> <span class="sc">|</span> pm_group<span class="sc">==</span><span class="dv">5</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(death <span class="sc">~</span> pm_group, <span class="at">data=</span>pm10winter<span class="fl">.15</span>, <span class="at">var.equal=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  death by pm_group
t = 1.2272, df = 217.98, p-value = 0.2211
alternative hypothesis: true difference in means between group 1 and group 5 is not equal to 0
95 percent confidence interval:
 -0.5344249  2.2980613
sample estimates:
mean in group 1 mean in group 5 
       22.23636        21.35455 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>pm10spring<span class="fl">.15</span> <span class="ot">=</span> pm10spring <span class="sc">%&gt;%</span> <span class="fu">filter</span>(pm_group<span class="sc">==</span><span class="dv">1</span> <span class="sc">|</span> pm_group<span class="sc">==</span><span class="dv">5</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(death <span class="sc">~</span> pm_group, <span class="at">data=</span>pm10spring<span class="fl">.15</span>, <span class="at">var.equal=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  death by pm_group
t = -0.71099, df = 216.92, p-value = 0.4779
alternative hypothesis: true difference in means between group 1 and group 5 is not equal to 0
95 percent confidence interval:
 -1.6506036  0.7754455
sample estimates:
mean in group 1 mean in group 5 
       18.55357        18.99115 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>pm10summer<span class="fl">.15</span> <span class="ot">=</span> pm10summer <span class="sc">%&gt;%</span> <span class="fu">filter</span>(pm_group<span class="sc">==</span><span class="dv">1</span> <span class="sc">|</span> pm_group<span class="sc">==</span><span class="dv">5</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(death <span class="sc">~</span> pm_group, <span class="at">data=</span>pm10summer<span class="fl">.15</span>, <span class="at">var.equal=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  death by pm_group
t = -3.4876, df = 207.04, p-value = 0.0005951
alternative hypothesis: true difference in means between group 1 and group 5 is not equal to 0
95 percent confidence interval:
 -3.5974049 -0.9990863
sample estimates:
mean in group 1 mean in group 5 
       17.63158        19.92982 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>pm10autumn<span class="fl">.15</span> <span class="ot">=</span> pm10autumn <span class="sc">%&gt;%</span> <span class="fu">filter</span>(pm_group<span class="sc">==</span><span class="dv">1</span> <span class="sc">|</span> pm_group<span class="sc">==</span><span class="dv">5</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(death <span class="sc">~</span> pm_group, <span class="at">data=</span>pm10autumn<span class="fl">.15</span>, <span class="at">var.equal=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  death by pm_group
t = -0.9771, df = 221, p-value = 0.3296
alternative hypothesis: true difference in means between group 1 and group 5 is not equal to 0
95 percent confidence interval:
 -2.1328719  0.7189401
sample estimates:
mean in group 1 mean in group 5 
       19.81982        20.52679 </code></pre>
</div>
</div>
</details></section>
<section id="section-4" class="level1">
<h1></h1>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>Data on Baltimore air pollution over a 19-year period were analyzed. The number of deaths that occurred on each day were recorded along with the level in the air of particulate matter of less than 10 micrometers in diameter (PM10 level). The average number of deaths between the lowest and highest quintile of PM10 level were compared across seasons (winter, spring, summer, autumn).</p>
<p>For all strata except summer, there is little indication of a difference in mean daily mortality between the lowest and highest pollution strata (p=0.22 for winter, p=0.48 for spring, p=0.33 for autumn). In summer, a difference in mean daily mortality between the lowest and highest pollution strata is strongly indicated (p=0.0006).</p>
<p>Although these data provide no evidence that the mean mortality differs by extreme pollution levels in winter, spring, and autumn for cities such as Baltimore, in the summer there appears to be strong evidence of a difference in the mean mortality for extreme pollution levels. In particular, there are an estimated 2.3 more deaths in the highest as compared to the lowest PM10 groups in summer.</p>
</section>
<section id="functions-used" class="level3">
<h3 class="anchored" data-anchor-id="functions-used">Functions used</h3>
<p>dyplr: filter, group_by, summarize, mean, ungroup</p>
<p>ggplot2: I am sorry I failed to make any plots. I’ve tried my best……😢</p>
</section>
<section id="referneces" class="level2">
<h2 class="anchored" data-anchor-id="referneces">Referneces</h2>
<ol type="1">
<li><p>Peng RD, Dominici F, Paster-Barriuso R, Zeger SL, Samet JM: Seasonal analysis of air pollution and mortality in 100 U.S. cities. American Journal of Epidemiology 16(6): 585-594, 2005.</p></li>
<li><p>Dominici F, McDermott A, Daniels M, Zeger SL, Samet JM. Revised analyses of the National Morbidity, Mortality, and Air Pollution Study: mortality among residents of 90 cities. J Toxicol Environ Health A. 2005 Jul 9-23;68(13-14):1071-92. doi: 10.1080/15287390590935932. PMID: 16024489.</p></li>
<li><p>Izzotti A, Spatera P, Khalid Z, Pulliero A. Importance of Punctual Monitoring to Evaluate the Health Effects of Airborne Particulate Matter. Int J Environ Res Public Health. 2022 Aug 25;19(17):10587. doi: 10.3390/ijerph191710587. PMID: 36078301; PMCID: PMC9518414.</p></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>